// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace WebApplication1.Migrations
{
    public partial class ChangeFilePath : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "PictureLocation",
                table: "People");

            migrationBuilder.AddColumn<string>(
                name: "FilePath",
                table: "People",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "FilePath",
                table: "People");

            migrationBuilder.AddColumn<string>(
                name: "PictureLocation",
                table: "People",
                type: "nvarchar(max)",
                nullable: true);
        }
    }
}
