// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace WebApplication1.Migrations
{
    public partial class ChangeSector : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM [People]", true);

            migrationBuilder.DropColumn(
                name: "Sector",
                table: "People");

            migrationBuilder.AddColumn<int>(
                name: "Sector",
                table: "People",
                nullable:false
                );

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
            name: "Sector",
            table: "People");


            migrationBuilder.AddColumn<string>(
                name: "Sector",
                table: "People",
                nullable: true
                );
        }
    }
}
